### ISSUE TITLE
Decide where Current will be hosted

### ISSUE THREAD

**Issue by aviflax** [arc90/current#1]
The most obvious options off the top of my head:
- self-hosted by Arc90 on Arc’s prod web machines at EC2
- Heroku

@closacco @jimniels any other options you think we should consider?

**Comment by closacco** [comment]
Nope, those are the two obvious ones.

**Comment by aviflax** [comment]
OK, so off the top of my head:

### Self-hosted

#### Pros
- Total flexibility
  - e.g. as to which DB we use (as in #2)
- If usage doesn’t take off, zero marginal cost
- Easy to migrate to any other infrastructure scenario which provides servers (as opposed to a PaaS)

#### Cons
- 100% manual deployment and operation (by default)
  - unless we use something like Puppet, Fabric, Grunt, Capistrano, etc, all deployment and ops tasks are 100% manual
- If usage takes off, scaling would be 100% manual
  - we’d have to manually launch new servers, deploy the components, configure replication, configure LBs, etc.

### Heroku

#### Pros
- If usage doesn’t take off, zero marginal cost
- If usage takes off, scaling is fast, easy, and automated
- Deployment and other ops tasks are fast, easy, and automated
- Easy to migrate to any other infrastructure scenario which provides servers (as opposed to a PaaS)

#### Cons
- Less flexibility around technologies and architecture
  - e.g. WRT #2 we’d want to use PostgreSQL, as that’s the only DBMS Heroku really supports
    - they sort-of support other DBMS’s via “add-ons” but I’m quite suspicious of them — unless I’m mistaken the add-on servers could be running in a different datacenter from the app servers, which just seems like a non-starter to me
  - e.g. if we want to use a task queue, we’d have to choose from one of the supported add-ons
- If usage takes off, and we need to scale out, would probably cost more than self-hosting

I’m also casually interested in considering Amazon’s [Elastic Beanstalk](https://aws.amazon.com/elasticbeanstalk/) and [OpsWorks](https://aws.amazon.com/opsworks/) solutions as middle grounds between raw EC2 and Heroku, but I’m not sure it’d be worth the time investment.

Right now I’m leaning towards Heroku.

@closacco any thoughts on all this?

**Comment by closacco** [comment]
> Right now I’m leaning towards Heroku.

+1.

**Comment by aviflax** [comment]
I’ve spoken with two Heroku staffers and they’ve convinced me that their add-ons are viable. So the first Heroku con is lessened. So it _would_ be viable to choose a DB other than PostgreSQL, such as CouchDB or RethinkDB.

Therefore I’m calling it: Heroku.

**Comment by closacco** [comment]
:+1:
